apiVersion: apps/v1
kind: Deployment
metadata:
  name: aksapp
  labels:
    app: aksapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aksapp
  template:
    metadata:
      labels:
        app: aksapp
    spec:
      containers:
        - name: frontend-app
          image: myregistry.azurecr.io/nginx:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
